---
output: html_document
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=5, echo=FALSE,message=FALSE ,warnings=FALSE)
```

### Label switching

### No mislabellings occuring

Dependent views and no mislabellings

```{r, eval=FALSE}
source("helpers.R")
source("par_updates.R")
source("MLFS_mcmc.R")
source("MLFS.R")
source("par_updates.R")
source("rotation.R")
source("generate_data.R")

Rcpp::sourceCpp("truncnorm.cpp")

H = rbind(c(1, 1, 0, 0), 
          c(0, 0, 1, 1), 
          c(1, 0, 1, 0), 
          c(1, 0, 0, 1)
          c(0, 0, 0, 1), 
          c(1, 0, 0, 0))

set.seed(1)
R = nrow(H)
d = c(10, 10, 10, 10)
type = rep("gaussian", 4)

latent_data = generate_latent_subspace(H, N = 200, d = d, gamma = 10)
y = generate_y(latent_data$V, C = 2, continuous = FALSE)
X0 = generate_X(latent_data$U_list, type)
data = split_into_train_and_test(X0, y, prop=0.5)
# random_selection = sample(1:length(data$trainy), 2) # which(data$trainy == 1)
# data$trainy[random_selection]
# changed_order = c(random_selection[-1], random_selection[1])
# data$trainX[[1]][random_selection, ] = data$trainX[[1]][changed_order, ]
MLFSobj = MLFS_mcmc(data$trainy, data$trainX, data$testy, data$testX, type, R, max_iter=5000, verbose=TRUE, label_switching = TRUE, marginal_sampler = FALSE)
label_state_mat = MLFSobj$label_state_mat[[1]]
save(label_state_mat, file="temp_label_state_mat1.RData")
```

Diagonal of the confusion matrix:

```{r}
load("temp_label_state_mat1.RData")
library(pheatmap)
as.numeric(round(diag(label_state_mat), 2))
pheatmap(label_state_mat, cluster_rows=F, cluster_cols=F, show_rownames=F, show_colnames=F)
```


Now, independent views and still no mislabellings

```{r, eval=FALSE}
H = rbind(c(1, 0, 0, 0), 
          c(0, 0, 0, 1), 
          c(1, 0, 0, 0), 
          c(0, 0, 1, 0)
          c(0, 0, 0, 1), 
          c(0, 1, 0, 0))

set.seed(0)
R = nrow(H)
d = c(10, 10, 10, 10)
type = rep("gaussian", 4)

latent_data = generate_latent_subspace(H, N = 200, d = d, gamma = 10)
y = generate_y(latent_data$V, C = 2, continuous = FALSE)
X0 = generate_X(latent_data$U_list, type)
data = split_into_train_and_test(X0, y, prop=0.5)
# random_selection = sample(1:length(data$trainy), 2) # which(data$trainy == 1)
# data$trainy[random_selection]
# changed_order = c(random_selection[-1], random_selection[1])
# data$trainX[[1]][random_selection, ] = data$trainX[[1]][changed_order, ]
MLFSobj = MLFS_mcmc(data$trainy, data$trainX, data$testy, data$testX, type, R, max_iter=5000, verbose=TRUE, label_switching = TRUE, marginal_sampler = FALSE)
label_state_mat = MLFSobj$label_state_mat[[1]]
save(label_state_mat, file="temp_label_state_mat2.RData")
```

```{r}
load("temp_label_state_mat2.RData")
as.numeric(round(diag(label_state_mat), 2))
pheatmap(label_state_mat, cluster_rows=F, cluster_cols=F, show_rownames=F, show_colnames=F)
```

### Some mislabellings

Switch labels (1, 2, 3, 4) to (2, 3, 4, 1). In this case, all of these belong to the same class

```{r, eval=FALSE}
H = rbind(c(1, 1, 0, 0), 
          c(0, 0, 1, 1), 
          c(1, 0, 1, 0), 
          c(1, 0, 0, 1)
          c(0, 0, 0, 1), 
          c(1, 0, 0, 0))

set.seed(1)
R = nrow(H)
d = c(10, 10, 10, 10)
type = rep("gaussian", 4)

latent_data = generate_latent_subspace(H, N = 200, d = d, gamma = 10)
y = generate_y(latent_data$V, C = 2, continuous = FALSE)
X0 = generate_X(latent_data$U_list, type)
data = split_into_train_and_test(X0, y, prop=0.5)
data$trainX[[1]][c(1, 2, 3, 4), ] = data$trainX[[1]][c(2, 3, 4, 1), ]
MLFSobj = MLFS_mcmc(data$trainy, data$trainX, data$testy, data$testX, type, R, max_iter=5000, verbose=TRUE, label_switching = TRUE, marginal_sampler = FALSE)
label_state_mat = MLFSobj$label_state_mat[[1]]
save(label_state_mat, file="temp_label_state_mat3.RData")

```

```{r}
load("temp_label_state_mat3.RData")
as.numeric(round(diag(label_state_mat), 2))
pheatmap(label_state_mat, cluster_rows=F, cluster_cols=F, show_rownames=F, show_colnames=F)
```

Switch labels (1, 5) to (5, 1). These are from a different class

```{r, eval=FALSE}
H = rbind(c(1, 1, 0, 0), 
          c(0, 0, 1, 1), 
          c(1, 0, 1, 0), 
          c(1, 0, 0, 1),
          c(0, 0, 0, 1), 
          c(1, 1, 0, 0))

set.seed(1)
R = nrow(H)
d = c(10, 10, 10, 10)
type = rep("gaussian", 4)

latent_data = generate_latent_subspace(H, N = 200, d = d, gamma = 10)
y = generate_y(latent_data$V, C = 2, continuous = FALSE)
X0 = generate_X(latent_data$U_list, type)
data = split_into_train_and_test(X0, y, prop=0.5)
data$trainX[[1]][c(1, 5), ] = data$trainX[[1]][c(5, 1), ]
MLFSobj = MLFS_mcmc(data$trainy, data$trainX, data$testy, data$testX, type, R, max_iter=5000, verbose=TRUE, label_switching = TRUE, marginal_sampler = FALSE)
label_state_mat = MLFSobj$label_state_mat[[1]]
save(label_state_mat, file="temp_label_state_mat4.RData")
```

```{r}
load("temp_label_state_mat4.RData")
as.numeric(round(diag(label_state_mat), 2))
pheatmap(label_state_mat, cluster_rows=F, cluster_cols=F, show_rownames=F, show_colnames=F)
```
